modLoader="javafml"
loaderVersion="${forge_range}"
license="${mod_license}"
issueTrackerURL="${issue_url}"
showAsResourcePack=false

[[mods]]
modId="slayersbeasts"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
#credits=""
description='''${mod_description}'''
logoFile="assets/logo.png"
displayURL="${homepage_url}"
#updateJSONURL=""
#displayTest="MATCH_VERSION"

[[dependencies.slayersbeasts]]
modId="minecraft"
mandatory=true
versionRange="${mc_range}"
ordering="NONE"
side="BOTH"

[[dependencies.slayersbeasts]]
modId="forge"
mandatory=true
versionRange="${forge_range}"
ordering="NONE"
side="BOTH"

[[dependencies.slayersbeasts]]
modId="terrablender"
mandatory=true
versionRange="[${tb_version},)"
ordering="NONE"
side="BOTH"