org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

curseforge_id=683329
modrinth_id=wveGP7nW
release_type=release

mod_id=slayersbeasts
mod_group=net.invictusslayer.slayersbeasts
mod_version=5.3.1
mod_name=Slayer's Beasts
mod_authors=InvictusSlayer
mod_credits=
mod_license=MIT
mod_description=Explore new structures and biomes to face off against beasts and bosses on the surface,\
  \nor in the treacherous dungeons below...
homepage_url=https://modrinth.com/mod/slayersbeasts
source_url=https://github.com/InvictusSlayer/Slayers-Beasts
issue_url=https://github.com/InvictusSlayer/Slayers-Beasts/issues

mc_version=1.21.1
mc_range=[1.21.1]
java_version=21

fabric_version=0.116.7+1.21.1
fabric_loader=0.19.3

forge_version=52.1.0
forge_range=[52,)

neo_version=21.1.241
neo_range=[21.1,)
neo_form=1.21.1-20240808.144430

parch_mc_version=1.21.1
parch_version=2024.11.17
scab_version=1.2.4
cloth_version=15.0.140
mm_version=11.0.3
tb_version=4.1.0.8
