modLoader="javafml"
loaderVersion="[45,)"
license="MIT"
issueTrackerURL="https://github.com/InvictusSlayer/Slayers-Beasts/issues"
showAsResourcePack=false

[[mods]]
modId="slayersbeasts"
version="${file.jarVersion}"
displayName="Slayer's Beasts"
#updateJSONURL=""
displayURL="https://modrinth.com/mod/slayers-beasts"
logoFile="slayersbeasts.png"
authors="InvictusSlayer"
credits="InkCxp for help building the structures"
description='''
Explore new structures and biomes to face off against beasts and bosses on the surface,
or in the treacherous dungeons below...
'''

[[dependencies.slayersbeasts]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.slayersbeasts]]
modId="forge"
mandatory=true
versionRange="[47.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.slayersbeasts]]
modId="terrablender"
mandatory=true
versionRange="[3.0.0.165,]"
ordering="NONE" # BEFORE/AFTER/NONE
side="BOTH" # CLIENT/SERVER/BOTH