modLoader="javafml"
loaderVersion="${project.forge_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/InvictusSlayer/Slayers-Beasts/issues"
showAsResourcePack=false

[[mods]]
modId="slayersbeasts"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL=""
displayURL="https://modrinth.com/mod/slayers-beasts"
logoFile="slayersbeasts.png"
authors="${mod_authors}"
credits="InkCxp for help building the structures"
displayTest="MATCH_VERSION" # MATCH_VERSION/IGNORE_SERVER_VERSION/IGNORE_ALL_VERSION/NONE
description='''${project.mod_desc}'''

[[dependencies.slayersbeasts]]
    modId="minecraft"
    mandatory=true
    versionRange="${project.mc_range}"
    ordering="NONE" # BEFORE/AFTER/NONE
    side="BOTH" # CLIENT/SERVER/BOTH

[[dependencies.slayersbeasts]]
    modId="forge"
    mandatory=true
    versionRange="${project.forge_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.slayersbeasts]]
    modId="terrablender"
    mandatory=true
    versionRange="[${project.tb_version},)"
    ordering="NONE"
    side="BOTH"