modLoader="javafml"
loaderVersion="[47.1,)"
license="MIT"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/slayersbeasts"
issueTrackerURL="https://github.com/InvictusSlayer/Slayers-Beasts/issues"
#updateJSONURL=""
logoFile="slayersbeasts.png"

[[mods]]
    modId="slayersbeasts"
    displayName="Slayer's Beasts"
    version="${file.jarVersion}"
    authors="InvictusSlayer"
    #credits=""
    description='''Battle with mobs and uncover deadly bosses
Try to survive the new biomes and structures
'''

[[dependencies.slayersbeasts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.slayersbeasts]]
    modId="forge"
    mandatory=true
    versionRange="[47.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.slayersbeasts]]
    modId="terrablender"
    mandatory=true
    versionRange="[3.0.0.165,]"
    ordering="NONE" # BEFORE or AFTER
    side="BOTH"