modLoader="javafml"
loaderVersion="[45,)"
license="MIT"
issueTrackerURL="https://github.com/InvictusSlayer/Slayers-Beasts/issues"

[[mods]]
modId="slayersbeasts"
version="${file.jarVersion}"
displayName="Slayer's Beasts"
#updateJSONURL=""
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/slayersbeasts"
logoFile="slayersbeasts.png"
authors="InvictusSlayer"
#credits=""
description='''
Battle relentless mobs and uncover new bosses
Try to survive the new biomes and structures as you traverse the world
'''

[[dependencies.slayersbeasts]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.slayersbeasts]]
modId="forge"
mandatory=true
versionRange="[47.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.slayersbeasts]]
modId="terrablender"
mandatory=true
versionRange="[3.0.0.165,]"
ordering="NONE" # BEFORE/AFTER/NONE
side="BOTH" # CLIENT/SERVER/BOTH