plugins {
    id "multiloader-loader"
    id "net.neoforged.moddev.legacyforge"
    id "com.hypherionmc.modutils.modpublisher" version "2.+"
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")
    config("${mod_id}-forge.mixins.json")
}

legacyForge {
    version = "${mc_version}-${forge_version}"

    validateAccessTransformers = true

    def at = project(":common").file("src/main/resources/META-INF/accesstransformer.cfg")
    if (at.exists()) {
        accessTransformers = [at.absolutePath]
    }
    parchment {
        minecraftVersion = parch_mc_version
        mappingsVersion = parch_version
    }
    runs {
        client {
            client()
        }
        data {
            data()
            programArguments.addAll "--mod", mod_id, "--all", "--output", file("src/main/generated/").getAbsolutePath(), "--existing", file("src/main/resources/").getAbsolutePath()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir "src/main/generated"

dependencies {
    compileOnly project(":common")
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")

    implementation("maven.modrinth:scabbard:${scab_version}+forge")
    implementation("com.github.glitchfiend:TerraBlender-forge:${mc_version}-${tb_version}")
    api("me.shedaniel.cloth:cloth-config-forge:${cloth_version}")
}

jar {
    finalizedBy("reobfJar")
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json,${mod_id}-forge.mixins.json"
    ])
}

publisher {
    apiKeys {
        modrinth System.getenv("MODRINTH_TOKEN")
        curseforge System.getenv("CURSEFORGE_TOKEN")
    }
    setCurseID("$curseforge_id")
    setModrinthID("$modrinth_id")
    setVersionType("$release_type")
    setChangelog(projectDir.toPath().parent.resolve("CHANGELOG.md").toFile().readLines().join("\n"))

    setDisplayName("$mod_name ${project.version} [Forge]")
    setVersion("${mod_version}+forge")
    setGameVersions("$mc_version")
    setLoaders("forge")

    setArtifact(jar)
    addAdditionalFile(sourcesJar)
    setCurseEnvironment("both")

    curseDepends {
        required "scabbard", "cloth-config", "terrablender-forge"
    }
    modrinthDepends {
        required "scabbard", "cloth-config", "terrablender"
    }
}