plugins {
    id "multiloader-loader"
    id "net.neoforged.moddev.legacyforge"
    id "com.hypherionmc.modutils.modpublisher" version "2.+"
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")
    config("${mod_id}-forge.mixins.json")
}

jar {
    finalizedBy("reobfJar")
    manifest {
        attributes["MixinConfigs"] = "${mod_id}.mixins.json,${mod_id}-forge.mixins.json"
    }
}

legacyForge {
    version = "${mc_version}-${forge_version}"

    validateAccessTransformers = true

    def at = project(":common").file("src/main/resources/META-INF/accesstransformer.cfg")
    if (at.exists()) accessTransformers = [at.absolutePath]
    parchment {
        minecraftVersion = parch_mc_version
        mappingsVersion = parch_version
    }
    runs {
        client {
            client()
        }
        data {
            data()
            programArguments.addAll "--all", "--mod", "${mod_id}"
            programArguments.addAll "--output", rootProject.project(":common").file("src/main/generated").absolutePath
            programArguments.addAll "--existing", file("src/main/resources").absolutePath
            programArguments.addAll "--existing", rootProject.project(":common").file("src/main/resources").absolutePath
            programArguments.addAll "--existing", rootProject.project(":common").file("src/main/generated").absolutePath
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir project(":common").file("src/main/generated").absolutePath

dependencies {
    compileOnly project(":common")
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.0"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.5.0"))

    modImplementation("maven.modrinth:scabbard:${scab_version}+forge")
    modImplementation("com.github.glitchfiend:TerraBlender-forge:${mc_version}-${tb_version}")
    api("me.shedaniel.cloth:cloth-config-forge:${cloth_version}")
}

publisher {
    apiKeys {
        modrinth System.getenv("MODRINTH_TOKEN")
        curseforge System.getenv("CURSEFORGE_TOKEN")
    }
    setCurseID("$curseforge_id")
    setModrinthID("$modrinth_id")
    setVersionType("$release_type")
    setChangelog(projectDir.toPath().parent.resolve("CHANGELOG.md").toFile().readLines().join("\n"))

    setDisplayName("$mod_name ${project.version} [Forge]")
    setVersion("${mod_version}+forge")
    setGameVersions("$mc_version")
    setLoaders("forge")

    setArtifact(jar)
    addAdditionalFile(sourcesJar)
    setCurseEnvironment("both")

    curseDepends {
        required "scabbard", "cloth-config", "terrablender-forge"
    }
    modrinthDepends {
        required "scabbard", "cloth-config", "terrablender"
    }
}