modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"
issueTrackerURL="${issue_url}"
showAsResourcePack=false

[[mods]]
modId="slayersbeasts"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_author}"
#credits=""
description='''${mod_description}'''
logoFile="assets/${mod_id}.png"
displayURL="${homepage_url}"
#updateJSONURL=""
#displayTest="MATCH_VERSION"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mixins]]
config="${mod_id}.mixins.json"
[[mixins]]
config="${mod_id}-neoforge.mixins.json"

[[dependencies.slayersbeasts]]
modId="minecraft"
type="required"
versionRange="${mc_range}"
ordering="NONE"
side="BOTH"

[[dependencies.slayersbeasts]]
modId="terrablender"
type="required"
versionRange="${tb_range}"
ordering="NONE"
side="BOTH"