modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"
issueTrackerURL="${issue_url}"
showAsResourcePack=false

[[mods]]
modId="slayersbeasts"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
#credits=""
description='''${mod_description}'''
logoFile="assets/${mod_id}.png"
displayURL="${homepage_url}"
#updateJSONURL=""
#displayTest="MATCH_VERSION"

[[mixins]]
config="slayersbeasts.mixins.json"
[[mixins]]
config="slayersbeasts-neoforge.mixins.json"

[[dependencies.slayersbeasts]]
modId="minecraft"
mandatory=true
versionRange="${mc_range}"
ordering="NONE"
side="BOTH"

[[dependencies.slayersbeasts]]
modId="neoforge"
mandatory=true
versionRange="${neo_range}"
ordering="NONE"
side="BOTH"

[[dependencies.slayersbeasts]]
modId = "architectury"
mandatory = true
versionRange = "[${arch_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.slayersbeasts]]
modId="terrablender"
mandatory=true
versionRange="[${tb_version},)"
ordering="NONE"
side="BOTH"