modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"
issueTrackerURL="${issue_url}"
showAsResourcePack=false

[[mods]]
modId="slayersbeasts"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
#credits="${mod_credits}"
description='''${mod_description}'''
logoFile="assets/logo.png"
displayURL="${homepage_url}"
#updateJSONURL=""
#displayTest="MATCH_VERSION"

[[mixins]]
config="slayersbeasts.mixins.json"
[[mixins]]
config="slayersbeasts-neoforge.mixins.json"

[[dependencies.slayersbeasts]]
modId="minecraft"
type="required"
versionRange="${mc_range}"
ordering="NONE"
side="BOTH"

[[dependencies.slayersbeasts]]
modId="neoforge"
type="required"
versionRange="${neo_range}"
ordering="NONE"
side="BOTH"

[[dependencies.slayersbeasts]]
modId="terrablender"
type="required"
versionRange="[${tb_version},)"
ordering="NONE"
side="BOTH"